## Python Assignment: Data Structures, Functions, Numpy & Pandas

## Section A: Data Structures & Control Structures

## 1.Create a list of 5 integers.Perform and print the result of the following operations: 
append, extend, insert, remove, pop, clear, index, count, sort, and reverse


In [33]:
# creating list of 5 integers
list1=[10,20,30,40,50]
list1

[10, 20, 30, 40, 50]

In [34]:
#append
list1.append(60) #appending the list1 by adding value 60
list1

[10, 20, 30, 40, 50, 60]

In [35]:
##extend
list1.extend([70]) #extending the list1 by adding value 70
list1

[10, 20, 30, 40, 50, 60, 70]

In [36]:
#insert
list1.insert(3,35) #inserting value 35 at index 3
list1

[10, 20, 30, 35, 40, 50, 60, 70]

In [37]:
#remove
list1.remove(70) #removing value 70 from list
list1

[10, 20, 30, 35, 40, 50, 60]

In [38]:
#pop
list1.pop(2) #poping value at index 2
list1

[10, 20, 35, 40, 50, 60]

In [39]:
#clear
list1.clear() #clearing the list1
list1

[]

In [40]:
#index
list1=[10,20,30,40,50]
list1.index(20) #finding the index value of 20

1

In [41]:
#count
list1.count(30) #counting the accurance of the number 30

1

In [42]:
#sort
list1=[50,60,30,10,80]
list1.sort() #sorting the values in list1 in ascending order
list1

[10, 30, 50, 60, 80]

In [43]:
#reverse
list1.reverse() #reversing the list1
list1

[80, 60, 50, 30, 10]

# 2.Create a tuple that stores 3 student names.Try changing the second name in the tuple. What happens? Explain why.



In [44]:
# creating the tuple that stores 3 students names
students = ("Rahul", "Priya", "Amit")
print(students)

('Rahul', 'Priya', 'Amit')


In [45]:
students[1]="jhon" #this will cause an error

TypeError: 'tuple' object does not support item assignment

- In Python, tuples are immutabletheir elements cannot be changed, added, or removed after creation.
- When you try to assign a new value (students[1] = "jhon"), 
- Python raises a TypeError because modification is not allowed.

## 3.Create a set of integers with some duplicate values. Print the set and explain the output.


In [ ]:
#creating set of integrs with duplicate values

numbers={10,20,30,20,50,10,80,30,60} 
print(numbers)
print("- A set in python automatically sorts and contains only unique elements")
print("- It removes the duplicate elements")

{80, 50, 20, 10, 60, 30}
- A set in python automatically sorts and contains only unique elements
- It removes the duplicate elements


## 4.Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary

In [ ]:
#creating dictonary with keys name, age and city

dict={
     'name':['ram','jhon','ramya','prem','rosie'],
     'age':['25','20','22','21','26','28'],
     'city':['Banglore','pune','chenai','delhi','up']  
    }
dict

{'name': ['ram', 'jhon', 'ramya', 'prem', 'rosie'],
 'age': ['25', '20', '22', '21', '26', '28'],
 'city': ['Banglore', 'pune', 'chenai', 'delhi', 'up']}

In [ ]:
#update age of index 2

dict['age'][2]=30
dict

{'name': ['ram', 'jhon', 'ramya', 'prem', 'rosie'],
 'age': ['25', '20', 30, '21', '26', '28'],
 'city': ['Banglore', 'pune', 'chenai', 'delhi', 'up']}

In [ ]:
#adding new key email

dict['email']=['ram@gmail.com','jhon@gmail.com','ramya@gmail.com','prem@gmail.com','rosie@gmail.com']

In [ ]:
#printing the final dictonary
dict

{'name': ['ram', 'jhon', 'ramya', 'prem', 'rosie'],
 'age': ['25', '20', 30, '21', '26', '28'],
 'city': ['Banglore', 'pune', 'chenai', 'delhi', 'up'],
 'email': ['ram@gmail.com',
  'jhon@gmail.com',
  'ramya@gmail.com',
  'prem@gmail.com',
  'rosie@gmail.com']}

## 5.Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message


In [ ]:
#program to checks if a person is eligible to vote (age ≥ 18)

age=int(input("enter the age of the person")) #takes the input age

if age>=18: 
    print("the perosn is eligible to vote")
else:
    print("the person is not elegible to vote!")
  

the perosn is eligible to vote


## 6.Given a 'marks' variable, print the grade:
#- 90 and above: 'A'
#- 75–89: 'B'
#- 50–74: 'C'
#- Below 50: 'Fail'

In [ ]:
#printing the grade according to the marks obtained

student_marks=int(input("enter the marks"))

if student_marks>=90:
    print("Grade:A")
elif student_marks>=75:
    print("Grade:B")
elif student_marks>=50:
    print("Grade:C")
elif student_marks<50:
    print("Fail!!")

Grade:B


## 7.Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.


In [ ]:
#Program to check if a number is positive, even, zero, or negative

n= int(input("enter the numbre"))

if n>0:
    if n%2==0:
        print("The number is positive and even")
    else:
        print("The number is positive but odd")    
elif n==0:
    print("The number is zero")
else:
    print("The number is negative")

The number is negative


## Section B: Numpy

## 8.Create:- A scalar using np.array(5)
 - A 1D array with values 1 to 5
 - A 2D array (2x3) with values from 10 to 60 in steps of 10

In [ ]:
import numpy as np
scalar=np.array(5)
print(scalar)

5


In [ ]:
#1d array with values 1 to 5
one_d=np.array([1,2,3,4,5])
print(one_d)

[1 2 3 4 5]


In [ ]:
#2d array with valuea from 10 to 60 
two_d=np.array([[10,20,30],
               [40,50,60]])
print(two_d)

[[10 20 30]
 [40 50 60]]


## 9.Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [ ]:
#generating numpy array of random integers between 0 amd 100
numbers=np.random.randint(0,100,16).reshape(4,4)
print(numbers)

[[85 79  3 81]
 [66 24 78 82]
 [96 86 12 80]
 [ 8 73 84 39]]


## 10.Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [ ]:
#creating 2d array of shape 3x3
two_d=np.random.randint(0,100,9).reshape(3,3)
print(two_d)

[[97 88 35]
 [31 38 97]
 [16 26 32]]


In [ ]:
#converting numpy array into pandas dataFrame and renaming the columns as A,B,C

import pandas as pd
  
df=pd.DataFrame(two_d,columns=['A','B','C'])  
df


A   B   C
0  97  88  35
1  31  38  97
2  16  26  32

## Section C: Exploring Pandas

## 11.Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'.
Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows

In [47]:
#creating the dictionary manualy
dict={
    'Name':['Ram','Priya','Jhon','Ram','Jack','Tina','Amith','Riya','Jhon','Meena'],
    'Age': [25, 28, 22, 25, 30, 25, 29, 22, 24, 27],
    'City': ['Delhi', 'Mumbai', 'Chennai', 'Delhi', 'Delhi', 'Delhi', 'Bangalore', 'Chennai', 'Pune', 'Mumbai'],
    'Salary': [45000, 52000, np.nan, 45000, 50000, 45000, 53000, 48000, np.nan, 51000]
}
dict

{'Name': ['Ram',
  'Priya',
  'Jhon',
  'Ram',
  'Jack',
  'Tina',
  'Amith',
  'Riya',
  'Jhon',
  'Meena'],
 'Age': [25, 28, 22, 25, 30, 25, 29, 22, 24, 27],
 'City': ['Delhi',
  'Mumbai',
  'Chennai',
  'Delhi',
  'Delhi',
  'Delhi',
  'Bangalore',
  'Chennai',
  'Pune',
  'Mumbai'],
 'Salary': [45000, 52000, nan, 45000, 50000, 45000, 53000, 48000, nan, 51000]}

In [48]:
import pandas as pd
import numpy as np

df=pd.DataFrame(dict) #converting th dict into Data Frame
df

Name  Age       City   Salary
0    Ram   25      Delhi  45000.0
1  Priya   28     Mumbai  52000.0
2   Jhon   22    Chennai      NaN
3    Ram   25      Delhi  45000.0
4   Jack   30      Delhi  50000.0
5   Tina   25      Delhi  45000.0
6  Amith   29  Bangalore  53000.0
7   Riya   22    Chennai  48000.0
8   Jhon   24       Pune      NaN
9  Meena   27     Mumbai  51000.0

In [49]:
#applying info()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes


In [50]:
# applying describe()
df.describe(include='all')

Name        Age   City        Salary
count    10  10.000000     10      8.000000
unique    8        NaN      5           NaN
top     Ram        NaN  Delhi           NaN
freq      2        NaN      4           NaN
mean    NaN  25.700000    NaN  48625.000000
std     NaN   2.750757    NaN   3335.416016
min     NaN  22.000000    NaN  45000.000000
25%     NaN  24.250000    NaN  45000.000000
50%     NaN  25.000000    NaN  49000.000000
75%     NaN  27.750000    NaN  51250.000000
max     NaN  30.000000    NaN  53000.000000

In [51]:
#selecting name and city columns

print(df[['Name','City']])


    Name       City
0    Ram      Delhi
1  Priya     Mumbai
2   Jhon    Chennai
3    Ram      Delhi
4   Jack      Delhi
5   Tina      Delhi
6  Amith  Bangalore
7   Riya    Chennai
8   Jhon       Pune
9  Meena     Mumbai


In [52]:
#droping column city

df.drop(columns=['City'])

Name  Age   Salary
0    Ram   25  45000.0
1  Priya   28  52000.0
2   Jhon   22      NaN
3    Ram   25  45000.0
4   Jack   30  50000.0
5   Tina   25  45000.0
6  Amith   29  53000.0
7   Riya   22  48000.0
8   Jhon   24      NaN
9  Meena   27  51000.0

In [53]:
# Fill any missing values in 'Salary' column with the mean

df['Salary'].fillna(df['Salary'].mean(), inplace=True)
df

C:\Users\prath\AppData\Local\Temp\ipykernel_25348\2588879366.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(df['Salary'].mean(), inplace=True)


Name  Age       City   Salary
0    Ram   25      Delhi  45000.0
1  Priya   28     Mumbai  52000.0
2   Jhon   22    Chennai  48625.0
3    Ram   25      Delhi  45000.0
4   Jack   30      Delhi  50000.0
5   Tina   25      Delhi  45000.0
6  Amith   29  Bangalore  53000.0
7   Riya   22    Chennai  48000.0
8   Jhon   24       Pune  48625.0
9  Meena   27     Mumbai  51000.0

In [56]:
#Removing any duplicate rows
df=df.drop_duplicates()
df = df.reset_index(drop=True)
df

Name  Age       City   Salary
0    Ram   25      Delhi  45000.0
1  Priya   28     Mumbai  52000.0
2   Jhon   22    Chennai  48625.0
3   Jack   30      Delhi  50000.0
4   Tina   25      Delhi  45000.0
5  Amith   29  Bangalore  53000.0
6   Riya   22    Chennai  48000.0
7   Jhon   24       Pune  48625.0
8  Meena   27     Mumbai  51000.0